<a href="https://colab.research.google.com/github/Anikeje2/Data-Science-Journey/blob/main/Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#First assignment
import numpy as np

In [ ]:
array = np.random.randint(0,100, size=(20,5)) #creating array of random numbers 0-100 in 20x5 shape
print (array)

[[74 63 28 94 50]
 [55 21 55 41 64]
 [37 27 15 53 18]
 [61 19 17 12 47]
 [23 14 28 95 57]
 [62 78 20 30 15]
 [50 73 43 89 51]
 [ 0 38 27 52 45]
 [85 93 57 25 30]
 [77 95 66 66 93]
 [18 31 58 38 92]
 [48 83 77 10 37]
 [ 2 92 92 50 78]
 [67 46 86 45 94]
 [69 99 52 81 66]
 [16 78 20 99 57]
 [97 16 39 71 35]
 [13 10 41  5 90]
 [27  2 93 27 90]
 [33 22 91 44 86]]

In [ ]:
clean = np.where(array>100 , 100 , array) #replacing all values greater than 100 with 100
print(clean)

[[74 63 28 94 50]
 [55 21 55 41 64]
 [37 27 15 53 18]
 [61 19 17 12 47]
 [23 14 28 95 57]
 [62 78 20 30 15]
 [50 73 43 89 51]
 [ 0 38 27 52 45]
 [85 93 57 25 30]
 [77 95 66 66 93]
 [18 31 58 38 92]
 [48 83 77 10 37]
 [ 2 92 92 50 78]
 [67 46 86 45 94]
 [69 99 52 81 66]
 [16 78 20 99 57]
 [97 16 39 71 35]
 [13 10 41  5 90]
 [27  2 93 27 90]
 [33 22 91 44 86]]

In [ ]:
clean2=np.where(array<0, 0, array) #replacing all values less than 0 with 0
print(clean2)

[[74 63 28 94 50]
 [55 21 55 41 64]
 [37 27 15 53 18]
 [61 19 17 12 47]
 [23 14 28 95 57]
 [62 78 20 30 15]
 [50 73 43 89 51]
 [ 0 38 27 52 45]
 [85 93 57 25 30]
 [77 95 66 66 93]
 [18 31 58 38 92]
 [48 83 77 10 37]
 [ 2 92 92 50 78]
 [67 46 86 45 94]
 [69 99 52 81 66]
 [16 78 20 99 57]
 [97 16 39 71 35]
 [13 10 41  5 90]
 [27  2 93 27 90]
 [33 22 91 44 86]]

In [ ]:
x= array.mean (axis = 1) #finding average for each student
print(x)
print(x>=75) #all average values >=75

[61.8 47.2 30.  31.2 43.4 41.  61.2 32.4 58.  79.4 47.4 51.  62.8 67.6
 73.4 54.  51.6 31.8 47.8 55.2]
[False False False False False False False False False  True False False
 False False False False False False False False]

In [ ]:
print(array.mean(axis=0)) #to find mean median and std of subjects
print(np.median(array,axis=0))
print(array.std(axis=0))

[45.7  50.   50.25 51.35 59.75]
[49.  42.  47.5 47.5 57. ]
[27.73283253 32.7001529  26.05546968 28.65881191 25.05568798]

Write a brief explanation of your approach and findings?

I generated a range of random scores for the students and calculated the average score for each student. I then filtered the results to identify students with an average score greater than or equal to 75; however, none of the students met this criterion, indicating generally average to low overall performance. Additionally, I computed the mean, median, and standard deviation for each student.

In [ ]:
 #Assignment 2 Pandas
import pandas as pd

In [ ]:
import csv
with open('students.csv', 'w') as file:   #to create csv file of student info
  student = csv.writer(file)
  student.writerow(['Name', 'Age', 'Math', 'Science', 'English'])
  student.writerow(['Fola', 15, 85, 90, 92])
  student.writerow(['Bolu', 16, 78, 88, 85])
  student.writerow(['Titi', 17, 92, 95, 91])
  student.writerow(['Lilian', 15, 70, 75, 78])
  student.writerow(['Chi', 16, 88, 92, 90])
  student.writerow(['Dele', 17, 95, 91, 88])
  student.writerow(['Grace', 15, 78, 85, 82])
  student.writerow(['Tina', 16, 92, 90, 88])
  student.writerow(['Ivy', 17, 85, 88, 92])

In [ ]:
df= pd.read_csv ('students.csv') #loading csv file to pandas
df.head()

     Name  Age  Math  Science  English
0    Fola   15    85       90       92
1    Bolu   16    78       88       85
2    Titi   17    92       95       91
3  Lilian   15    70       75       78
4     Chi   16    88       92       90

In [ ]:
df['Total'] = df['English']+df['Math']+df['Science']  #finding sum of all scores and including Total column
df.head()

     Name  Age  Math  Science  English  Total
0    Fola   15    85       90       92    267
1    Bolu   16    78       88       85    251
2    Titi   17    92       95       91    278
3  Lilian   15    70       75       78    223
4     Chi   16    88       92       90    270

In [ ]:
df['Average'] =  df['Total']/3    #finding and adding average columns
df.head()

     Name  Age  Math  Science  English  Total    Average
0    Fola   15    85       90       92    267  89.000000
1    Bolu   16    78       88       85    251  83.666667
2    Titi   17    92       95       91    278  92.666667
3  Lilian   15    70       75       78    223  74.333333
4     Chi   16    88       92       90    270  90.000000

In [ ]:
greater_avg=df[df['Average']>=80] #average greater than or equal to 80
greater_avg

    Name  Age  Math  Science  English  Total    Average
0   Fola   15    85       90       92    267  89.000000
1   Bolu   16    78       88       85    251  83.666667
2   Titi   17    92       95       91    278  92.666667
4    Chi   16    88       92       90    270  90.000000
5   Dele   17    95       91       88    274  91.333333
6  Grace   15    78       85       82    245  81.666667
7   Tina   16    92       90       88    270  90.000000
8    Ivy   17    85       88       92    265  88.333333

In [ ]:
greater_avg.to_csv('greater_avg.csv', index=False) # saving avg >=80 to new csv file

In [ ]:
top_three = df.sort_values(by='Average', ascending=False).head(3) # to get top three students

top_three.to_json('top_three.json', orient ='records', indent=2) #to save top3 to json file
top_three

   Name  Age  Math  Science  English  Total    Average
2  Titi   17    92       95       91    278  92.666667
5  Dele   17    95       91       88    274  91.333333
7  Tina   16    92       90       88    270  90.000000

In [ ]:
# Assignment 3
from google.colab import drive
import pandas as pd
import numpy as np
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/SCA class/students_messy_data.csv')
df.head() #to load messy data onto the notebook

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount
0,1032,Emma,Thomas,18.0,male,student1032@university.edu,Kano,27/08/2022,Science,4.00,55.0,43.0,78.0,Inactive,12905
1,1110,William,Thomas,24.0,female,student1110@university.edu,Enugu,17/05/2020,Business,3.38,48.0,88.0,77.0,Active,38256
2,1137,Sophia,Rodriguez,18.0,male,student1137@university.edu,Port Harcourt,08/08/2021,Science,3.07,49.0,63.0,52.0,Graduated,10751
3,1089,Thomas,Martinez,21.0,female,student1089@university.edu,Ibadan,19/10/2023,Law,NaN,59.0,65.0,94.0,Active,47607
4,1919,Mia,Garcia,21.0,M,student1919@university.edu,Kano,NaN,Education,2.90,44.0,NaN,59.0,On Leave,36203

In [ ]:
print("\n Percentage missing for each column \n") #finding missing data per column
print(df.isnull().sum()/df.shape[0]*100)

 Percentage missing for each column

StudentID             0.000000
FirstName             0.000000
LastName              0.000000
Age                  10.291262
Gender                7.281553
Email                 0.000000
City                 12.330097
EnrollmentDate        7.766990
Department            0.000000
GPA                  13.980583
Math                  5.922330
English               8.058252
Science               5.631068
Status                0.000000
ScholarshipAmount     0.000000
dtype: float64

In [ ]:
# handling age missing data
mean_age = df['Age'].mean()
df['Age'].fillna(mean_age, inplace=True)
df.head()

/tmp/ipython-input-260/3740288847.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(mean_age, inplace=True)

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount
0,1032,Emma,Thomas,18.0,male,student1032@university.edu,Kano,27/08/2022,Science,4.00,55.0,43.0,78.0,Inactive,12905
1,1110,William,Thomas,24.0,female,student1110@university.edu,Enugu,17/05/2020,Business,3.38,48.0,88.0,77.0,Active,38256
2,1137,Sophia,Rodriguez,18.0,male,student1137@university.edu,Port Harcourt,08/08/2021,Science,3.07,49.0,63.0,52.0,Graduated,10751
3,1089,Thomas,Martinez,21.0,female,student1089@university.edu,Ibadan,19/10/2023,Law,NaN,59.0,65.0,94.0,Active,47607
4,1919,Mia,Garcia,21.0,M,student1919@university.edu,Kano,NaN,Education,2.90,44.0,NaN,59.0,On Leave,36203

In [ ]:
#handling missing scores
english_score = pd.to_numeric(df["English"], errors="coerce").median()
df["English"].fillna(english_score, inplace=True)

/tmp/ipython-input-260/3833540384.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["English"].fillna(english_score, inplace=True)

In [ ]:
#handling missing scores
math_score = pd.to_numeric(df["Math"], errors="coerce").median()
df["Math"].fillna(math_score, inplace=True)

/tmp/ipython-input-260/2277745800.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Math"].fillna(math_score, inplace=True)

In [ ]:
#handling missing scores
sci_score = pd.to_numeric(df["Science"], errors="coerce").median()
df["Science"].fillna(sci_score, inplace=True)

/tmp/ipython-input-260/3299188482.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Science"].fillna(sci_score, inplace=True)

In [ ]:
#handling missing GPA
median_gpa = pd.to_numeric(df["GPA"], errors="coerce").median()
df["GPA"].fillna(median_gpa, inplace=True)

/tmp/ipython-input-260/3248675796.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["GPA"].fillna(median_gpa, inplace=True)

In [ ]:
#handling missing Gender nd city
df["Gender"] = df["Gender"].fillna("Unknown")
df["City"] = df["City"].fillna("Unknown")

In [ ]:
df['EnrollmentDate'].fillna(pd.to_datetime('02-03-2026'), inplace=True)
 #replacing all missing data with todays date
df.head()

/tmp/ipython-input-260/1508111855.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['EnrollmentDate'].fillna(pd.to_datetime('02-03-2026'), inplace=True)

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount
0,1032,Emma,Thomas,18.0,male,student1032@university.edu,Kano,27/08/2022,Science,4.00,55.0,43.0,78.0,Inactive,12905
1,1110,William,Thomas,24.0,female,student1110@university.edu,Enugu,17/05/2020,Business,3.38,48.0,88.0,77.0,Active,38256
2,1137,Sophia,Rodriguez,18.0,male,student1137@university.edu,Port Harcourt,08/08/2021,Science,3.07,49.0,63.0,52.0,Graduated,10751
3,1089,Thomas,Martinez,21.0,female,student1089@university.edu,Ibadan,19/10/2023,Law,2.99,59.0,65.0,94.0,Active,47607
4,1919,Mia,Garcia,21.0,M,student1919@university.edu,Kano,2026-02-03 00:00:00,Education,2.90,44.0,71.0,59.0,On Leave,36203

In [ ]:
print(df.isnull().sum()/df.shape[0]*100)

StudentID            0.0
FirstName            0.0
LastName             0.0
Age                  0.0
Gender               0.0
Email                0.0
City                 0.0
EnrollmentDate       0.0
Department           0.0
GPA                  0.0
Math                 0.0
English              0.0
Science              0.0
Status               0.0
ScholarshipAmount    0.0
dtype: float64

In [ ]:
#converting data types
print(df['StudentID'].dtype)
print(df['FirstName'].dtype)
print(df['LastName'].dtype)
print(df['Age'].dtype)
print(df['Gender'].dtype)
print(df['Email'].dtype)
print(df['City'].dtype)
print(df['EnrollmentDate'].dtype)
print(df['Department'].dtype)
print(df['GPA'].dtype)
print(df['Math'].dtype)
print(df['English'].dtype)
print(df['Science'].dtype)
print(df['Status'].dtype)
print(df['ScholarshipAmount'].dtype)

int64
object
object
float64
object
object
object
object
object
float64
float64
float64
float64
object
int64

In [ ]:
#converting data type
df['StudentID'] = df['StudentID'].astype(str)
print(df['StudentID'].dtype)

df['Age'] = df['Age'].astype(int)
print(df['Age'].dtype)

object
int64

In [ ]:
#standardizing text
df['Gender']= df['Gender'].replace('male','M')
df['Gender']= df['Gender'].replace('female','F')
df['Gender']= df['Gender'].replace('Male','M')
df['Gender']= df['Gender'].replace('Female','F')
df.head(5)

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount
0,1032,Emma,Thomas,18,M,student1032@university.edu,Kano,27/08/2022,Science,4.00,55.0,43.0,78.0,Inactive,12905
1,1110,William,Thomas,24,F,student1110@university.edu,Enugu,17/05/2020,Business,3.38,48.0,88.0,77.0,Active,38256
2,1137,Sophia,Rodriguez,18,M,student1137@university.edu,Port Harcourt,08/08/2021,Science,3.07,49.0,63.0,52.0,Graduated,10751
3,1089,Thomas,Martinez,21,F,student1089@university.edu,Ibadan,19/10/2023,Law,2.99,59.0,65.0,94.0,Active,47607
4,1919,Mia,Garcia,21,M,student1919@university.edu,Kano,2026-02-03 00:00:00,Education,2.90,44.0,71.0,59.0,On Leave,36203

In [ ]:
df['FirstName'] = df['FirstName'].str.strip() #removing whitespaces from all strings
df['LastName'] = df['LastName'].str.strip()
df['Gender'] = df['Gender'].str.strip()
df['Email'] = df['Email'].str.strip()
df['City'] = df['City'].str.strip()
df['Department'] = df['Department'].str.strip()
df['Status'] = df['Status'].str.strip()

In [ ]:
df["EnrollmentDate"] = pd.to_datetime(df["EnrollmentDate"], errors="coerce")
print(df["EnrollmentDate"].dtype)

datetime64[ns]

/tmp/ipython-input-260/2474503097.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["EnrollmentDate"] = pd.to_datetime(df["EnrollmentDate"], errors="coerce")

In [ ]:
df['Total'] = df['English']+df['Math']+df['Science']  #finding sum of all scores and including Total column
df.head()

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount,Total
0,1032,Emma,Thomas,18,M,student1032@university.edu,Kano,2022-08-27,Science,4.00,55.0,43.0,78.0,Inactive,12905,176.0
1,1110,William,Thomas,24,F,student1110@university.edu,Enugu,2020-05-17,Business,3.38,48.0,88.0,77.0,Active,38256,213.0
2,1137,Sophia,Rodriguez,18,M,student1137@university.edu,Port Harcourt,2021-08-08,Science,3.07,49.0,63.0,52.0,Graduated,10751,164.0
3,1089,Thomas,Martinez,21,F,student1089@university.edu,Ibadan,2023-10-19,Law,2.99,59.0,65.0,94.0,Active,47607,218.0
4,1919,Mia,Garcia,21,M,student1919@university.edu,Kano,2026-02-03,Education,2.90,44.0,71.0,59.0,On Leave,36203,174.0

In [ ]:
df['Avg_scores'] =  df['Total']/3    #finding and adding average columns
df.head()

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount,Total,Avg_scores
0,1032,Emma,Thomas,18,M,student1032@university.edu,Kano,2022-08-27,Science,4.00,55.0,43.0,78.0,Inactive,12905,176.0,58.666667
1,1110,William,Thomas,24,F,student1110@university.edu,Enugu,2020-05-17,Business,3.38,48.0,88.0,77.0,Active,38256,213.0,71.000000
2,1137,Sophia,Rodriguez,18,M,student1137@university.edu,Port Harcourt,2021-08-08,Science,3.07,49.0,63.0,52.0,Graduated,10751,164.0,54.666667
3,1089,Thomas,Martinez,21,F,student1089@university.edu,Ibadan,2023-10-19,Law,2.99,59.0,65.0,94.0,Active,47607,218.0,72.666667
4,1919,Mia,Garcia,21,M,student1919@university.edu,Kano,2026-02-03,Education,2.90,44.0,71.0,59.0,On Leave,36203,174.0,58.000000

In [ ]:
active_std= df[df['Status']=='Active'] #filtering all active students
print(active_std)

     StudentID    FirstName   LastName  Age   Gender  \
1         1110      William     Thomas   24        F
3         1089       Thomas   Martinez   21        F
5         1686      Matthew      Brown   23        M
9         1536     Isabella   Anderson   23        M
11        1597     Isabella      Davis   22        M
...        ...          ...        ...  ...      ...
1009      1460  Christopher  Hernandez   20  Unknown
1011      1277     Isabella  Rodriguez   21  Unknown
1015      1806  Christopher  Rodriguez   21        F
1016      1414       Harper      Brown   18        M
1029      1861      Matthew      Lopez   21        F

                           Email           City EnrollmentDate  \
1     student1110@university.edu          Enugu     2020-05-17
3     student1089@university.edu         Ibadan     2023-10-19
5     student1686@university.edu            Aba     2021-04-26
9     student1536@university.edu            Aba     2022-12-07
11    student1597@university.edu           Kano     2020-08-21
...                          ...            ...            ...
1009  student1460@university.edu          Enugu     2022-06-07
1011  student1277@university.edu         Kaduna     2021-05-31
1015  student1806@university.edu        Unknown     2020-10-09
1016  student1414@university.edu  Port Harcourt     2020-11-20
1029  student1861@university.edu        Unknown     2021-08-09

            Department   GPA   Math  English  Science  Status  \
1             Business  3.38   48.0     88.0     77.0  Active
3                  Law  2.99   59.0     65.0     94.0  Active
5          Engineering  3.87   52.0     79.0     69.0  Active
9             Business  2.99   68.0     48.0     47.0  Active
11           Education  2.44   44.0     57.0     80.0  Active
...                ...   ...    ...      ...      ...     ...
1009  Computer Science  3.48  100.0     90.0     45.0  Active
1011          Business  2.46   83.0    100.0     82.0  Active
1015  Computer Science  3.74   93.0     71.0     94.0  Active
1016              Arts  2.82   90.0     69.0     91.0  Active
1029  Computer Science  3.82   88.0     93.0     83.0  Active

      ScholarshipAmount  Total  Avg_scores
1                 38256  213.0   71.000000
3                 47607  218.0   72.666667
5                  6953  200.0   66.666667
9                  4594  163.0   54.333333
11                46646  181.0   60.333333
...                 ...    ...         ...
1009              22588  235.0   78.333333
1011               5618  265.0   88.333333
1015              27500  258.0   86.000000
1016              11705  250.0   83.333333
1029               2985  264.0   88.000000

[262 rows x 17 columns]

In [ ]:
mean_gpa = df['GPA'].mean() #calculating mean GPA
print(mean_gpa)

2.9916213592233007

In [ ]:
mean_total =df['Total'].mean()
print(mean_total)

209.7495145631068

In [ ]:
print(df.describe())

               Age                 EnrollmentDate          GPA         Math  \
count  1030.000000                           1030  1030.000000  1030.000000
mean     21.421359  2022-05-26 09:13:37.864077568     2.991621    69.690291
min      18.000000            2020-01-01 00:00:00     2.010000    40.000000
25%      20.000000            2021-02-19 12:00:00     2.525000    56.000000
50%      21.000000            2022-04-20 00:00:00     2.990000    69.000000
75%      23.000000            2023-05-22 18:00:00     3.427500    84.000000
max      25.000000            2026-02-03 00:00:00     4.000000   100.000000
std       2.214259                            NaN     0.547861    17.080448

           English      Science  ScholarshipAmount        Total   Avg_scores
count  1030.000000  1030.000000        1030.000000  1030.000000  1030.000000
mean     70.446602    69.612621       25202.676699   209.749515    69.916505
min      40.000000    40.000000          82.000000   129.000000    43.000000
25%      57.000000    56.000000       12760.500000   189.250000    63.083333
50%      71.000000    69.000000       25523.000000   210.000000    70.000000
75%      84.750000    84.000000       36895.500000   230.000000    76.666667
max     100.000000   100.000000       49996.000000   292.000000    97.333333
std      16.869088    17.025917       14398.161544    29.185766     9.728589

In [ ]:
conditions = [df['English'] >= 70, (df['English'] < 70) & (df['English'] >= 55), (df['English'] < 55) & (df['English'] >= 45)]
choices = ['A', 'B', 'C']
df['EnglishGrade'] = np.select(conditions, choices, default='D')
df.head() #Assigning grades to scores 70 and above is A, and less 70 to 55 is B, C is less than 55 to 45 and others is D

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount,Total,Avg_scores,EnglishGrade
0,1032,Emma,Thomas,18,M,student1032@university.edu,Kano,2022-08-27,Science,4.00,55.0,43.0,78.0,Inactive,12905,176.0,58.666667,D
1,1110,William,Thomas,24,F,student1110@university.edu,Enugu,2020-05-17,Business,3.38,48.0,88.0,77.0,Active,38256,213.0,71.000000,A
2,1137,Sophia,Rodriguez,18,M,student1137@university.edu,Port Harcourt,2021-08-08,Science,3.07,49.0,63.0,52.0,Graduated,10751,164.0,54.666667,B
3,1089,Thomas,Martinez,21,F,student1089@university.edu,Ibadan,2023-10-19,Law,2.99,59.0,65.0,94.0,Active,47607,218.0,72.666667,B
4,1919,Mia,Garcia,21,M,student1919@university.edu,Kano,2026-02-03,Education,2.90,44.0,71.0,59.0,On Leave,36203,174.0,58.000000,A

In [ ]:
conditions = [df['Math'] >= 70, (df['Math'] < 70) & (df['Math'] >= 55), (df['Math'] < 55) & (df['Math'] >= 45)]
choices = ['A', 'B', 'C']
df['MathGrade'] = np.select(conditions, choices, default='D')
df.head()

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount,Total,Avg_scores,EnglishGrade,MathGrade
0,1032,Emma,Thomas,18,M,student1032@university.edu,Kano,2022-08-27,Science,4.00,55.0,43.0,78.0,Inactive,12905,176.0,58.666667,D,B
1,1110,William,Thomas,24,F,student1110@university.edu,Enugu,2020-05-17,Business,3.38,48.0,88.0,77.0,Active,38256,213.0,71.000000,A,C
2,1137,Sophia,Rodriguez,18,M,student1137@university.edu,Port Harcourt,2021-08-08,Science,3.07,49.0,63.0,52.0,Graduated,10751,164.0,54.666667,B,C
3,1089,Thomas,Martinez,21,F,student1089@university.edu,Ibadan,2023-10-19,Law,2.99,59.0,65.0,94.0,Active,47607,218.0,72.666667,B,B
4,1919,Mia,Garcia,21,M,student1919@university.edu,Kano,2026-02-03,Education,2.90,44.0,71.0,59.0,On Leave,36203,174.0,58.000000,A,D

In [ ]:
conditions = [df['Science'] >= 70, (df['Science'] < 70) & (df['Science'] >= 55), (df['Science'] < 55) & (df['Science'] >= 45)]
choices = ['A', 'B', 'C']
df['ScienceGrade'] = np.select(conditions, choices, default='D')
df.head()

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount,Total,Avg_scores,EnglishGrade,MathGrade,ScienceGrade
0,1032,Emma,Thomas,18,M,student1032@university.edu,Kano,2022-08-27,Science,4.00,55.0,43.0,78.0,Inactive,12905,176.0,58.666667,D,B,A
1,1110,William,Thomas,24,F,student1110@university.edu,Enugu,2020-05-17,Business,3.38,48.0,88.0,77.0,Active,38256,213.0,71.000000,A,C,A
2,1137,Sophia,Rodriguez,18,M,student1137@university.edu,Port Harcourt,2021-08-08,Science,3.07,49.0,63.0,52.0,Graduated,10751,164.0,54.666667,B,C,C
3,1089,Thomas,Martinez,21,F,student1089@university.edu,Ibadan,2023-10-19,Law,2.99,59.0,65.0,94.0,Active,47607,218.0,72.666667,B,B,A
4,1919,Mia,Garcia,21,M,student1919@university.edu,Kano,2026-02-03,Education,2.90,44.0,71.0,59.0,On Leave,36203,174.0,58.000000,A,D,B

Documentation
 To clean and prepare the dataset, I first assessed missing values across all columns to understand where gaps existed. For numerical data, I used the mean for Age and the median for scores and CGPA to preserve distribution integrity. Categorical fields like Gender and City were filled with "Unknown" to avoid assumptions, while all string columns were stripped of extra spaces and standardized for consistency. Missing Enrollment Dates were replaced with a placeholder to maintain chronological completeness. I also converted all columns to their correct data types and created new features, including Total and Average Scores, alongside a letter grading system (A–D) based on student performance. Finally, the dataset was filtered to include only Active students, ensuring the analysis focuses on the current student body.