<a href="https://colab.research.google.com/github/Anikeje2/Data-Science-Journey/blob/main/Learning_data_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
import pandas as pd
drive.mount('/content/drive') #)to mount data

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/SCA class/students_messy_data.csv')
df.head()

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount
0,1032,Emma,Thomas,18.0,male,student1032@university.edu,Kano,27/08/2022,Science,4.00,55.0,43.0,78.0,Inactive,12905
1,1110,William,Thomas,24.0,female,student1110@university.edu,Enugu,17/05/2020,Business,3.38,48.0,88.0,77.0,Active,38256
2,1137,Sophia,Rodriguez,18.0,male,student1137@university.edu,Port Harcourt,08/08/2021,Science,3.07,49.0,63.0,52.0,Graduated,10751
3,1089,Thomas,Martinez,21.0,female,student1089@university.edu,Ibadan,19/10/2023,Law,NaN,59.0,65.0,94.0,Active,47607
4,1919,Mia,Garcia,21.0,M,student1919@university.edu,Kano,NaN,Education,2.90,44.0,NaN,59.0,On Leave,36203

In [ ]:
print(df.isnull().sum) #)to show sum of all missing data as true or false

<bound method DataFrame.sum of       StudentID  FirstName  LastName    Age  Gender  Email   City  \
0         False      False     False  False   False  False  False
1         False      False     False  False   False  False  False
2         False      False     False  False   False  False  False
3         False      False     False  False   False  False  False
4         False      False     False  False   False  False  False
...         ...        ...       ...    ...     ...    ...    ...
1025      False      False     False  False   False  False   True
1026      False      False     False  False   False  False  False
1027      False      False     False  False   False  False  False
1028      False      False     False  False   False  False  False
1029      False      False     False  False   False  False   True

      EnrollmentDate  Department    GPA   Math  English  Science  Status  \
0              False       False  False  False    False    False   False
1              False       False  False  False    False    False   False
2              False       False  False  False    False    False   False
3              False       False   True  False    False    False   False
4               True       False  False  False     True    False   False
...              ...         ...    ...    ...      ...      ...     ...
1025           False       False  False  False    False    False   False
1026           False       False  False  False    False    False   False
1027            True       False  False  False    False    False   False
1028           False       False   True  False    False    False   False
1029           False       False  False  False    False    False   False

      ScholarshipAmount
0                 False
1                 False
2                 False
3                 False
4                 False
...                 ...
1025              False
1026              False
1027              False
1028              False
1029              False

[1030 rows x 15 columns]>

In [ ]:
print(df.isnull().sum() / df.shape[0]*100) #)to calculate percentage of missing data

StudentID            0.000000
FirstName            0.000000
LastName             0.000000
Age                  0.000000
Gender               0.000000
Email                0.000000
City                 0.000000
EnrollmentDate       7.766990
Department           0.000000
GPA                  0.000000
Math                 5.922330
English              8.058252
Science              5.631068
Status               0.000000
ScholarshipAmount    0.000000
dtype: float64

In [ ]:
print(df.isnull().sum().sum()) #)to get actual amount of missing data

734

In [ ]:
values= df.dropna()
print(values)

      StudentID FirstName   LastName   Age  Gender  \
0          1032      Emma     Thomas  18.0    male
1          1110   William   Thomas    24.0  female
2          1137    Sophia  Rodriguez  18.0    male
6          1871      Emma    Johnson  22.0    male
8          1262     David     Wilson  23.0  Female
...         ...       ...        ...   ...     ...
1008       1314       Mia  Rodriguez  24.0    male
1016       1414    Harper      Brown  18.0       M
1020       1309   Michael    Jackson  25.0  female
1023       1664    Amelia      Brown  23.0  female
1026       1331       Mia   Martinez  18.0       M

                           Email           City EnrollmentDate   Department  \
0     student1032@university.edu           Kano     27/08/2022      Science
1     student1110@university.edu          Enugu     17/05/2020     Business
2     student1137@university.edu  Port Harcourt     08/08/2021      Science
6     student1871@university.edu          Abuja     04/01/2022         Arts
8     student1262@university.edu           Kano     20/12/2020  Engineering
...                          ...            ...            ...          ...
1008  student1314@university.edu          Lagos     07/05/2021     Business
1016  student1414@university.edu  Port Harcourt     20/11/2020         Arts
1020  student1309@university.edu         Ibadan     27/08/2023    Education
1023  student1664@university.edu          Lagos     09/06/2023     Business
1026  student1331@university.edu         Ibadan     09/04/2023  Engineering

       GPA  Math  English  Science     Status  ScholarshipAmount
0     4.00  55.0     43.0     78.0   Inactive              12905
1     3.38  48.0     88.0     77.0     Active              38256
2     3.07  49.0     63.0     52.0  Graduated              10751
6     3.94  50.0     80.0     53.0   Inactive               3968
8     2.62  47.0     50.0     56.0   Inactive              43370
...    ...   ...      ...      ...        ...                ...
1008  3.84  62.0     48.0     46.0  Graduated              39579
1016  2.82  90.0     69.0     91.0     Active              11705
1020  2.90  48.0     53.0     92.0   Inactive              10655
1023  3.49  69.0     82.0     73.0  Graduated              25530
1026  2.45  88.0     77.0     47.0   On Leave              29100

[469 rows x 15 columns]

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          1030 non-null   int64
 1   FirstName          1030 non-null   object
 2   LastName           1030 non-null   object
 3   Age                924 non-null    float64
 4   Gender             955 non-null    object
 5   Email              1030 non-null   object
 6   City               903 non-null    object
 7   EnrollmentDate     950 non-null    object
 8   Department         1030 non-null   object
 9   GPA                886 non-null    float64
 10  Math               969 non-null    float64
 11  English            947 non-null    float64
 12  Science            972 non-null    float64
 13  Status             1030 non-null   object
 14  ScholarshipAmount  1030 non-null   int64
dtypes: float64(5), int64(2), object(8)
memory usage: 120.8+ KB
None

In [ ]:
df_clean = df.dropna(how="all")

In [ ]:
mean_age= df["Age"].mean()
print(f"the mean age is: {mean_age}")

the mean age is: 21.46969696969697

In [ ]:
mean_age =df["Age"].astype(float,errors= "ignore").mean()
df["Age"].fillna(mean_age, inplace=True)

df.head() #)to fill up all age missing data

/tmp/ipython-input-605/1690706178.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(mean_age, inplace=True)

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount
0,1032,Emma,Thomas,18.0,male,student1032@university.edu,Kano,27/08/2022,Science,4.00,55.0,43.0,78.0,Inactive,12905
1,1110,William,Thomas,24.0,female,student1110@university.edu,Enugu,17/05/2020,Business,3.38,48.0,88.0,77.0,Active,38256
2,1137,Sophia,Rodriguez,18.0,male,student1137@university.edu,Port Harcourt,08/08/2021,Science,3.07,49.0,63.0,52.0,Graduated,10751
3,1089,Thomas,Martinez,21.0,female,student1089@university.edu,Ibadan,19/10/2023,Law,NaN,59.0,65.0,94.0,Active,47607
4,1919,Mia,Garcia,21.0,M,student1919@university.edu,Kano,NaN,Education,2.90,44.0,NaN,59.0,On Leave,36203

In [ ]:
mode_gender = df["Gender"].mode()[0]
df["Gender"].fillna(mode_gender, inplace=True)
df.head()

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount
0,1032,Emma,Thomas,18.0,male,student1032@university.edu,Kano,27/08/2022,Science,4.00,55.0,43.0,78.0,Inactive,12905
1,1110,William,Thomas,24.0,female,student1110@university.edu,Enugu,17/05/2020,Business,3.38,48.0,88.0,77.0,Active,38256
2,1137,Sophia,Rodriguez,18.0,male,student1137@university.edu,Port Harcourt,08/08/2021,Science,3.07,49.0,63.0,52.0,Graduated,10751
3,1089,Thomas,Martinez,21.0,female,student1089@university.edu,Ibadan,19/10/2023,Law,NaN,59.0,65.0,94.0,Active,47607
4,1919,Mia,Garcia,21.0,M,student1919@university.edu,Kano,NaN,Education,2.90,44.0,NaN,59.0,On Leave,36203

In [ ]:
df["City"].fillna("Unknown", inplace=True)
df.head()

/tmp/ipython-input-605/1733261325.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["City"].fillna("Unknown", inplace=True)

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount
0,1032,Emma,Thomas,18.0,male,student1032@university.edu,Kano,27/08/2022,Science,4.00,55.0,43.0,78.0,Inactive,12905
1,1110,William,Thomas,24.0,female,student1110@university.edu,Enugu,17/05/2020,Business,3.38,48.0,88.0,77.0,Active,38256
2,1137,Sophia,Rodriguez,18.0,male,student1137@university.edu,Port Harcourt,08/08/2021,Science,3.07,49.0,63.0,52.0,Graduated,10751
3,1089,Thomas,Martinez,21.0,female,student1089@university.edu,Ibadan,19/10/2023,Law,NaN,59.0,65.0,94.0,Active,47607
4,1919,Mia,Garcia,21.0,M,student1919@university.edu,Kano,NaN,Education,2.90,44.0,NaN,59.0,On Leave,36203

In [ ]:
mean_gpa= pd.to_numeric(df["GPA"], errors ="coerce").mean()
df["GPA"].fillna(mean_gpa, inplace=True)
df.head()

/tmp/ipython-input-605/2966034744.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["GPA"].fillna(mean_gpa, inplace=True)

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount
0,1032,Emma,Thomas,18.0,male,student1032@university.edu,Kano,27/08/2022,Science,4.000000,55.0,43.0,78.0,Inactive,12905
1,1110,William,Thomas,24.0,female,student1110@university.edu,Enugu,17/05/2020,Business,3.380000,48.0,88.0,77.0,Active,38256
2,1137,Sophia,Rodriguez,18.0,male,student1137@university.edu,Port Harcourt,08/08/2021,Science,3.070000,49.0,63.0,52.0,Graduated,10751
3,1089,Thomas,Martinez,21.0,female,student1089@university.edu,Ibadan,19/10/2023,Law,2.991885,59.0,65.0,94.0,Active,47607
4,1919,Mia,Garcia,21.0,M,student1919@university.edu,Kano,NaN,Education,2.900000,44.0,NaN,59.0,On Leave,36203

In [ ]:
mean_gpa= pd.to_numeric(df["Math"], errors ="coerce").median()
df["Math"].fillna(mean_gpa, inplace=True)
df.head()

/tmp/ipython-input-605/2387966990.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Math"].fillna(mean_gpa, inplace=True)

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount
0,1032,Emma,Thomas,18.0,male,student1032@university.edu,Kano,27/08/2022,Science,4.000000,55.0,43.0,78.0,Inactive,12905
1,1110,William,Thomas,24.0,female,student1110@university.edu,Enugu,17/05/2020,Business,3.380000,48.0,88.0,77.0,Active,38256
2,1137,Sophia,Rodriguez,18.0,male,student1137@university.edu,Port Harcourt,08/08/2021,Science,3.070000,49.0,63.0,52.0,Graduated,10751
3,1089,Thomas,Martinez,21.0,female,student1089@university.edu,Ibadan,19/10/2023,Law,2.991885,59.0,65.0,94.0,Active,47607
4,1919,Mia,Garcia,21.0,M,student1919@university.edu,Kano,NaN,Education,2.900000,44.0,NaN,59.0,On Leave,36203

In [ ]:
mean_gpa= pd.to_numeric(df["Math"], errors ="coerce").median()
df["Math"].fillna(mean_gpa, inplace=True)
df.head()

In [ ]:
print(df.isnull().sum())

StudentID             0
FirstName             0
LastName              0
Age                   0
Gender                0
Email                 0
City                  0
EnrollmentDate       80
Department            0
GPA                   0
Math                  0
English              83
Science              58
Status                0
ScholarshipAmount     0
dtype: int64

In [ ]:
print(df.isnull().sum()/df.shape[0]*100)

StudentID             0.000000
FirstName             0.000000
LastName              0.000000
Age                   0.000000
Gender                0.000000
Email                 0.000000
City                 12.330097
EnrollmentDate        7.766990
Department            0.000000
GPA                  13.980583
Math                  5.922330
English               8.058252
Science               5.631068
Status                0.000000
ScholarshipAmount     0.000000
dtype: float64

In [ ]:
mean_age= df ["Age"].astype(float, errors="ignore").mean()
df["Age"].fillna(mean_age, inplace=True)
df.head()

/tmp/ipython-input-605/3529813392.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(mean_age, inplace=True)

,StudentID,FirstName,LastName,Age,Gender,Email,City,EnrollmentDate,Department,GPA,Math,English,Science,Status,ScholarshipAmount
0,1032,Emma,Thomas,18.0,male,student1032@university.edu,Kano,27/08/2022,Science,4.00,55.0,43.0,78.0,Inactive,12905
1,1110,William,Thomas,24.0,female,student1110@university.edu,Enugu,17/05/2020,Business,3.38,48.0,88.0,77.0,Active,38256
2,1137,Sophia,Rodriguez,18.0,male,student1137@university.edu,Port Harcourt,08/08/2021,Science,3.07,49.0,63.0,52.0,Graduated,10751
3,1089,Thomas,Martinez,21.0,female,student1089@university.edu,Ibadan,19/10/2023,Law,NaN,59.0,65.0,94.0,Active,47607
4,1919,Mia,Garcia,21.0,M,student1919@university.edu,Kano,NaN,Education,2.90,44.0,NaN,59.0,On Leave,36203

In [ ]:
mode_gender = df["Gender"].mode()[0]
df["Gender"].fillna(mode_gender , inplace=True)

/tmp/ipython-input-605/729079462.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].fillna(mode_gender , inplace=True)

In [ ]:
missing_scores = dropna(subset=["Math"])